name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            image: go-sync
            platforms: linux/amd64,linux/arm64
          - dockerfile: dynamo.Dockerfile
            image: go-sync-dynamo
            platforms: linux/amd64
          - dockerfile: dynamo.rpi.Dockerfile
            image: go-sync-dynamo
            platforms: linux/arm64
            tag-suffix: -rpi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push ${{ matrix.image }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest${{ matrix.tag-suffix }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:${{ github.sha }}${{ matrix.tag-suffix }}
